/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.7.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as UserService from "../UserService.js";
import type * as asset from "../asset.js";
import type * as battle from "../battle.js";
import type * as bgames from "../bgames.js";
import type * as crons from "../crons.js";
import type * as events from "../events.js";
import type * as gameService from "../gameService.js";
import type * as games from "../games.js";
import type * as gameseed from "../gameseed.js";
import type * as leaderboard from "../leaderboard.js";
import type * as tournamentService from "../tournamentService.js";
import type * as tournaments from "../tournaments.js";
import type * as user from "../user.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  UserService: typeof UserService;
  asset: typeof asset;
  battle: typeof battle;
  bgames: typeof bgames;
  crons: typeof crons;
  events: typeof events;
  gameService: typeof gameService;
  games: typeof games;
  gameseed: typeof gameseed;
  leaderboard: typeof leaderboard;
  tournamentService: typeof tournamentService;
  tournaments: typeof tournaments;
  user: typeof user;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
