/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.0.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as asset from "../asset";
import type * as battle from "../battle";
import type * as battleService from "../battleService";
import type * as bgames from "../bgames";
import type * as crons from "../crons";
import type * as events from "../events";
import type * as games from "../games";
import type * as gameseed from "../gameseed";
import type * as gameService from "../gameService";
import type * as leaderboard from "../leaderboard";
import type * as tournaments from "../tournaments";
import type * as tournamentService from "../tournamentService";
import type * as user from "../user";
import type * as UserService from "../UserService";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  asset: typeof asset;
  battle: typeof battle;
  battleService: typeof battleService;
  bgames: typeof bgames;
  crons: typeof crons;
  events: typeof events;
  games: typeof games;
  gameseed: typeof gameseed;
  gameService: typeof gameService;
  leaderboard: typeof leaderboard;
  tournaments: typeof tournaments;
  tournamentService: typeof tournamentService;
  user: typeof user;
  UserService: typeof UserService;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
